wallpaper {
    # 用于显示此壁纸的显示器, 如果为空, 将使用此壁纸作为备用
    monitor =
    # 指向一个图像文件或包含图像文件(非递归)的目录的路径
    path = ~/Pictures/Wallpapers/wallpaper.png
    # 图像显示模式
    # contain: 按比例缩放图像, 使完整图像显示在容器内, 容器可能留有空白区域, 图像不变形
    # cover: 按比例缩放图像, 使其完全覆盖容器, 图像可能被裁剪, 图像不变形, 此为默认值
    # fill: 伸图像以完全填充容器, 不保持宽高比, 图像可能发生变形
    # tile: 不对图像进行缩放, 以原始尺寸重复平铺, 直到填满整个容器, 若图像比容器大, 只显示部分图像
    fit_mode = cover
}
# 在壁纸上方渲染 hyprland 启动画面
splash = false
